/**
 * Master of Acupuncture and Herbal Medicine (MAHM) — catalog-style course list.
 * Didactic/lab: units × $200; clinical: hours × $17 (see billingService).
 */

export const MAHM_COURSES = [
  {
    courseId: 'MAHM101',
    courseCode: 'TCM101',
    title: 'Foundations of Traditional Chinese Medicine',
    type: 'didactic',
    units: 3,
  },
  {
    courseId: 'MAHM102',
    courseCode: 'ACU201',
    title: 'Acupuncture Techniques I',
    type: 'didactic',
    units: 4,
  },
  {
    courseId: 'MAHM103',
    courseCode: 'ACU202',
    title: 'Acupuncture Techniques II',
    type: 'didactic',
    units: 4,
  },
  {
    courseId: 'MAHM104',
    courseCode: 'HERB201',
    title: 'Chinese Herbology I — Materia Medica',
    type: 'didactic',
    units: 3,
  },
  {
    courseId: 'MAHM105',
    courseCode: 'HERB202',
    title: 'Chinese Herbology II — Formulas',
    type: 'didactic',
    units: 3,
  },
  {
    courseId: 'MAHM106',
    courseCode: 'POI201',
    title: 'Meridian Theory and Point Location I',
    type: 'didactic',
    units: 2,
  },
  {
    courseId: 'MAHM107',
    courseCode: 'POI202',
    title: 'Meridian Theory and Point Location II',
    type: 'didactic',
    units: 2,
  },
  {
    courseId: 'MAHM108',
    courseCode: 'DXM201',
    title: 'TCM Pattern Differentiation and Diagnosis',
    type: 'didactic',
    units: 3,
  },
  {
    courseId: 'MAHM109',
    courseCode: 'BIO201',
    title: 'Biomedicine for Acupuncturists I',
    type: 'didactic',
    units: 3,
  },
  {
    courseId: 'MAHM110',
    courseCode: 'BIO202',
    title: 'Biomedicine for Acupuncturists II',
    type: 'didactic',
    units: 3,
  },
  {
    courseId: 'MAHM111',
    courseCode: 'ETH301',
    title: 'Professionalism, Ethics, and Practice Management',
    type: 'didactic',
    units: 2,
  },
  {
    courseId: 'MAHM112',
    courseCode: 'RES301',
    title: 'Evidence and Research in East Asian Medicine',
    type: 'didactic',
    units: 2,
  },
  {
    courseId: 'MAHM113',
    courseCode: 'ACULAB1',
    title: 'Acupuncture Techniques Laboratory I',
    type: 'lab',
    units: 1,
  },
  {
    courseId: 'MAHM114',
    courseCode: 'HERBLAB1',
    title: 'Herbal Preparation Laboratory',
    type: 'lab',
    units: 1,
  },
  {
    courseId: 'CLINIC1',
    courseCode: 'CLN301',
    title: 'Clinical Internship Level 1',
    type: 'clinical',
    hours: 90,
  },
  {
    courseId: 'CLINIC2',
    courseCode: 'CLN302',
    title: 'Clinical Internship Level 2',
    type: 'clinical',
    hours: 120,
  },
  {
    courseId: 'CLINIC3',
    courseCode: 'CLN303',
    title: 'Clinical Internship Level 3',
    type: 'clinical',
    hours: 150,
  },
]
